- name: configure cart
  hosts: cart
  become: yes
  tasks:
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create system cart
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
        path: /app
        state: absent
      
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete cart zip file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent
      
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: Unarchive a file 
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
    
  - name: Install packages
    community.general.npm:
      path: /app

  - name: copy cart service 
    ansible.builtin.template:
      src: cart.service 
      dest: /etc/systemd/system/cart.service

  - name: system daemon reloaded
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: cart

  - name: start and enable cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes
