- name: configuring frontend
  hosts: frontend
  become: yes
  tasks:
  - name: enable nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: delete html file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
      
  - name: Download frontend
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: Unarchive frontend
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: remove default nginx
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf

  - name: copy nginx
    ansible.builtin.template:
      src: nginx.config
      dest: /etc/nginx/nginx.conf
      

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes

  
