- name: configuring payment
  hosts: payment
  become: yes
  tasks:
  - name: install python
    ansible.builtin.dnf:
      name: "{{ item }}"
    loop:
    - python3
    - gcc
    - python3-devel

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
        path: /app
        state: absent
      
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete payment zip file
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent
      
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: Unarchive a file 
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes
