- name: configure rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq
      dest: /etc/yum.repos.d/rabbitmq.repo
      remote_src: yes
  - name: install rabbitmq server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present
  - name: creating user and password
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present

  - name: start and enable rabbitmq 
    ansible.builtin.service:
      name: rabbitmq-server
      state: restarted
      enabled: yes
      