- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-0b7199557ac4e0337
    domain_name: daws88s.store
    instances:
    - mongodb
    - catalogue
    env: dev
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        component: "{{ item }}"
        Env: "{{ env }}"
        name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print thr ec2 output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env}}.{{ domain_name }}" # mongodb-dev.daws88s.store
      type: A 
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"