- name: configure user
  hosts: user
  become: yes
  tasks: 
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  